// IPC Channel definitions
export const IPC_CHANNELS = {
  TRACKING: {
    START: 'tracking:start',
    STOP: 'tracking:stop',
    GET_STATUS: 'tracking:get-status',
    WINDOW_CHANGED: 'tracking:window-changed',
    IDLE_CHANGED: 'tracking:idle-changed',
    STATE_CHANGED: 'tracking:state-changed',
    IDLE_PROMPT: 'tracking:idle-prompt'
  },
  ANALYTICS: {
    GET_TODAY: 'analytics:get-today',
    GET_RANGE: 'analytics:get-range',
    GET_TOP_APPS: 'analytics:get-top-apps',
    GET_CATEGORIES: 'analytics:get-categories',
    GET_HOURLY: 'analytics:get-hourly',
    GET_HOURLY_BY_CATEGORY: 'analytics:get-hourly-by-category',
    GET_DAILY: 'analytics:get-daily',
    GET_DAILY_BY_CATEGORY: 'analytics:get-daily-by-category'
  },
  SETTINGS: {
    GET: 'settings:get',
    UPDATE: 'settings:update'
  },
  CATEGORIES: {
    GET_ALL: 'categories:get-all',
    GET_WITH_STATS: 'categories:get-with-stats',
    CREATE: 'categories:create',
    UPDATE: 'categories:update',
    DELETE: 'categories:delete'
  },
  APPLICATIONS: {
    GET_ALL: 'applications:get-all',
    GET_ALL_WITH_TIME: 'applications:get-all-with-time',
    UPDATE_CATEGORY: 'applications:update-category',
    SET_TRACKED: 'applications:set-tracked'
  },
  GOALS: {
    GET_ALL: 'goals:get-all',
    GET_ACTIVE: 'goals:get-active',
    GET_BY_ID: 'goals:get-by-id',
    CREATE: 'goals:create',
    UPDATE: 'goals:update',
    DELETE: 'goals:delete',
    SET_ACTIVE: 'goals:set-active',
    GET_PROGRESS: 'goals:get-progress',
    UPDATE_PROGRESS: 'goals:update-progress',
    GET_WARNINGS: 'goals:get-warnings',
    SYNC_PROGRESS: 'goals:sync-progress'
  },
  FOCUS: {
    GET_ALL: 'focus:get-all',
    GET_BY_ID: 'focus:get-by-id',
    GET_ACTIVE: 'focus:get-active',
    GET_TODAY: 'focus:get-today',
    GET_STATS: 'focus:get-stats',
    GET_HISTORY: 'focus:get-history',
    START: 'focus:start',
    PAUSE: 'focus:pause',
    RESUME: 'focus:resume',
    COMPLETE: 'focus:complete',
    CANCEL: 'focus:cancel',
    ADD_BREAK: 'focus:add-break',
    UPDATE_NOTES: 'focus:update-notes',
    DELETE: 'focus:delete'
  },
  LIMITS: {
    GET_ALL: 'limits:get-all',
    GET_BY_CATEGORY: 'limits:get-by-category',
    UPSERT: 'limits:upsert',
    DELETE: 'limits:delete',
    CHECK_STATUS: 'limits:check-status',
    WARNING: 'limits:warning',
    EXCEEDED: 'limits:exceeded',
    BLOCKED: 'limits:blocked'
  },
  SCREENSHOTS: {
    GET_ALL: 'screenshots:get-all',
    GET_BY_ID: 'screenshots:get-by-id',
    GET_BY_DATE_RANGE: 'screenshots:get-by-date-range',
    GET_BY_APP: 'screenshots:get-by-app',
    DELETE: 'screenshots:delete',
    DELETE_OLD: 'screenshots:delete-old',
    TAKE_MANUAL: 'screenshots:take-manual',
    GET_SETTINGS: 'screenshots:get-settings',
    UPDATE_SETTINGS: 'screenshots:update-settings',
    GET_STATS: 'screenshots:get-stats'
  },
  PROJECTS: {
    GET_ALL: 'projects:get-all',
    GET_ACTIVE: 'projects:get-active',
    GET_BY_ID: 'projects:get-by-id',
    GET_WITH_STATS: 'projects:get-with-stats',
    GET_ALL_WITH_STATS: 'projects:get-all-with-stats',
    CREATE: 'projects:create',
    UPDATE: 'projects:update',
    DELETE: 'projects:delete',
    ARCHIVE: 'projects:archive',
    RESTORE: 'projects:restore',
    // Rules
    GET_RULES: 'projects:get-rules',
    CREATE_RULE: 'projects:create-rule',
    UPDATE_RULE: 'projects:update-rule',
    DELETE_RULE: 'projects:delete-rule',
    // Matching & Time
    MATCH_PROJECT: 'projects:match-project',
    GET_PROJECT_TIME: 'projects:get-project-time',
    ASSIGN_TO_ENTRY: 'projects:assign-to-entry',
    // Billing
    GET_BILLING_REPORT: 'projects:get-billing-report',
    GET_BUDGET_STATUS: 'projects:get-budget-status',
    GET_BUDGET_WARNINGS: 'projects:get-budget-warnings'
  },
  CALENDAR: {
    GET_ALL: 'calendar:get-all',
    GET_BY_ID: 'calendar:get-by-id',
    GET_BY_DATE_RANGE: 'calendar:get-by-date-range',
    GET_BY_DAY: 'calendar:get-by-day',
    CREATE: 'calendar:create',
    UPDATE: 'calendar:update',
    DELETE: 'calendar:delete',
    // Views
    GET_WEEK_VIEW: 'calendar:get-week-view',
    GET_MONTH_VIEW: 'calendar:get-month-view',
    // Time correlation
    GET_EVENT_APP_USAGE: 'calendar:get-event-app-usage',
    FORMAT_EVENT_USAGE: 'calendar:format-event-usage'
  },
  NOTIFICATIONS: {
    SEND: 'notifications:send',
    GET_HISTORY: 'notifications:get-history',
    CLEAR_HISTORY: 'notifications:clear-history',
    RESET_BREAK_TIMER: 'notifications:reset-break-timer'
  },
  PRIVACY: {
    GET_EXCLUDED_APPS: 'privacy:get-excluded-apps',
    ADD_EXCLUDED_APP: 'privacy:add-excluded-app',
    REMOVE_EXCLUDED_APP: 'privacy:remove-excluded-app',
    GET_EXCLUDED_PATTERNS: 'privacy:get-excluded-patterns',
    ADD_EXCLUDED_PATTERN: 'privacy:add-excluded-pattern',
    REMOVE_EXCLUDED_PATTERN: 'privacy:remove-excluded-pattern',
    GET_PRIVATE_MODE: 'privacy:get-private-mode',
    SET_PRIVATE_MODE: 'privacy:set-private-mode',
    GET_DATA_RETENTION: 'privacy:get-data-retention',
    SET_DATA_RETENTION: 'privacy:set-data-retention',
    EXPORT_ALL_DATA: 'privacy:export-all-data',
    DELETE_ALL_DATA: 'privacy:delete-all-data',
    APPLY_DATA_RETENTION: 'privacy:apply-data-retention',
    PRIVATE_MODE_CHANGED: 'privacy:private-mode-changed'
  },
  SHORTCUTS: {
    GET_ALL: 'shortcuts:get-all',
    GET_BY_ID: 'shortcuts:get-by-id',
    UPDATE: 'shortcuts:update',
    RESET_ALL: 'shortcuts:reset-all',
    SET_ENABLED: 'shortcuts:set-enabled',
    TRIGGERED: 'shortcuts:triggered'
  },
  THEMES: {
    GET_CURRENT: 'themes:get-current',
    SET_THEME: 'themes:set-theme',
    GET_AVAILABLE: 'themes:get-available'
  },
  APP: {
    MINIMIZE: 'app:minimize',
    MAXIMIZE: 'app:maximize',
    CLOSE: 'app:close',
    QUIT: 'app:quit',
    GET_VERSION: 'app:get-version',
    NAVIGATE: 'navigate',
    GET_ONBOARDING_STATUS: 'app:get-onboarding-status',
    SET_ONBOARDING_COMPLETE: 'app:set-onboarding-complete'
  }
} as const;

// Channel whitelist for preload validation
export const SEND_CHANNELS = [
  IPC_CHANNELS.APP.MINIMIZE,
  IPC_CHANNELS.APP.MAXIMIZE,
  IPC_CHANNELS.APP.CLOSE,
  IPC_CHANNELS.APP.QUIT
];

export const INVOKE_CHANNELS = [
  IPC_CHANNELS.TRACKING.START,
  IPC_CHANNELS.TRACKING.STOP,
  IPC_CHANNELS.TRACKING.GET_STATUS,
  IPC_CHANNELS.ANALYTICS.GET_TODAY,
  IPC_CHANNELS.ANALYTICS.GET_RANGE,
  IPC_CHANNELS.ANALYTICS.GET_TOP_APPS,
  IPC_CHANNELS.ANALYTICS.GET_CATEGORIES,
  IPC_CHANNELS.ANALYTICS.GET_HOURLY,
  IPC_CHANNELS.ANALYTICS.GET_HOURLY_BY_CATEGORY,
  IPC_CHANNELS.ANALYTICS.GET_DAILY,
  IPC_CHANNELS.ANALYTICS.GET_DAILY_BY_CATEGORY,
  IPC_CHANNELS.SETTINGS.GET,
  IPC_CHANNELS.SETTINGS.UPDATE,
  IPC_CHANNELS.CATEGORIES.GET_ALL,
  IPC_CHANNELS.CATEGORIES.GET_WITH_STATS,
  IPC_CHANNELS.CATEGORIES.CREATE,
  IPC_CHANNELS.CATEGORIES.UPDATE,
  IPC_CHANNELS.CATEGORIES.DELETE,
  IPC_CHANNELS.APPLICATIONS.GET_ALL,
  IPC_CHANNELS.APPLICATIONS.GET_ALL_WITH_TIME,
  IPC_CHANNELS.APPLICATIONS.UPDATE_CATEGORY,
  IPC_CHANNELS.APPLICATIONS.SET_TRACKED,
  IPC_CHANNELS.GOALS.GET_ALL,
  IPC_CHANNELS.GOALS.GET_ACTIVE,
  IPC_CHANNELS.GOALS.GET_BY_ID,
  IPC_CHANNELS.GOALS.CREATE,
  IPC_CHANNELS.GOALS.UPDATE,
  IPC_CHANNELS.GOALS.DELETE,
  IPC_CHANNELS.GOALS.SET_ACTIVE,
  IPC_CHANNELS.GOALS.GET_PROGRESS,
  IPC_CHANNELS.GOALS.UPDATE_PROGRESS,
  IPC_CHANNELS.GOALS.GET_WARNINGS,
  IPC_CHANNELS.GOALS.SYNC_PROGRESS,
  IPC_CHANNELS.FOCUS.GET_ALL,
  IPC_CHANNELS.FOCUS.GET_BY_ID,
  IPC_CHANNELS.FOCUS.GET_ACTIVE,
  IPC_CHANNELS.FOCUS.GET_TODAY,
  IPC_CHANNELS.FOCUS.GET_STATS,
  IPC_CHANNELS.FOCUS.GET_HISTORY,
  IPC_CHANNELS.FOCUS.START,
  IPC_CHANNELS.FOCUS.PAUSE,
  IPC_CHANNELS.FOCUS.RESUME,
  IPC_CHANNELS.FOCUS.COMPLETE,
  IPC_CHANNELS.FOCUS.CANCEL,
  IPC_CHANNELS.FOCUS.ADD_BREAK,
  IPC_CHANNELS.FOCUS.UPDATE_NOTES,
  IPC_CHANNELS.FOCUS.DELETE,
  IPC_CHANNELS.LIMITS.GET_ALL,
  IPC_CHANNELS.LIMITS.GET_BY_CATEGORY,
  IPC_CHANNELS.LIMITS.UPSERT,
  IPC_CHANNELS.LIMITS.DELETE,
  IPC_CHANNELS.LIMITS.CHECK_STATUS,
  IPC_CHANNELS.SCREENSHOTS.GET_ALL,
  IPC_CHANNELS.SCREENSHOTS.GET_BY_ID,
  IPC_CHANNELS.SCREENSHOTS.GET_BY_DATE_RANGE,
  IPC_CHANNELS.SCREENSHOTS.GET_BY_APP,
  IPC_CHANNELS.SCREENSHOTS.DELETE,
  IPC_CHANNELS.SCREENSHOTS.DELETE_OLD,
  IPC_CHANNELS.SCREENSHOTS.TAKE_MANUAL,
  IPC_CHANNELS.SCREENSHOTS.GET_SETTINGS,
  IPC_CHANNELS.SCREENSHOTS.UPDATE_SETTINGS,
  IPC_CHANNELS.SCREENSHOTS.GET_STATS,
  // Projects
  IPC_CHANNELS.PROJECTS.GET_ALL,
  IPC_CHANNELS.PROJECTS.GET_ACTIVE,
  IPC_CHANNELS.PROJECTS.GET_BY_ID,
  IPC_CHANNELS.PROJECTS.GET_WITH_STATS,
  IPC_CHANNELS.PROJECTS.GET_ALL_WITH_STATS,
  IPC_CHANNELS.PROJECTS.CREATE,
  IPC_CHANNELS.PROJECTS.UPDATE,
  IPC_CHANNELS.PROJECTS.DELETE,
  IPC_CHANNELS.PROJECTS.ARCHIVE,
  IPC_CHANNELS.PROJECTS.RESTORE,
  IPC_CHANNELS.PROJECTS.GET_RULES,
  IPC_CHANNELS.PROJECTS.CREATE_RULE,
  IPC_CHANNELS.PROJECTS.UPDATE_RULE,
  IPC_CHANNELS.PROJECTS.DELETE_RULE,
  IPC_CHANNELS.PROJECTS.MATCH_PROJECT,
  IPC_CHANNELS.PROJECTS.GET_PROJECT_TIME,
  IPC_CHANNELS.PROJECTS.ASSIGN_TO_ENTRY,
  IPC_CHANNELS.PROJECTS.GET_BILLING_REPORT,
  IPC_CHANNELS.PROJECTS.GET_BUDGET_STATUS,
  IPC_CHANNELS.PROJECTS.GET_BUDGET_WARNINGS,
  // Calendar
  IPC_CHANNELS.CALENDAR.GET_ALL,
  IPC_CHANNELS.CALENDAR.GET_BY_ID,
  IPC_CHANNELS.CALENDAR.GET_BY_DATE_RANGE,
  IPC_CHANNELS.CALENDAR.GET_BY_DAY,
  IPC_CHANNELS.CALENDAR.CREATE,
  IPC_CHANNELS.CALENDAR.UPDATE,
  IPC_CHANNELS.CALENDAR.DELETE,
  IPC_CHANNELS.CALENDAR.GET_WEEK_VIEW,
  IPC_CHANNELS.CALENDAR.GET_MONTH_VIEW,
  IPC_CHANNELS.CALENDAR.GET_EVENT_APP_USAGE,
  IPC_CHANNELS.CALENDAR.FORMAT_EVENT_USAGE,
  // Notifications
  IPC_CHANNELS.NOTIFICATIONS.SEND,
  IPC_CHANNELS.NOTIFICATIONS.GET_HISTORY,
  IPC_CHANNELS.NOTIFICATIONS.CLEAR_HISTORY,
  IPC_CHANNELS.NOTIFICATIONS.RESET_BREAK_TIMER,
  // Privacy
  IPC_CHANNELS.PRIVACY.GET_EXCLUDED_APPS,
  IPC_CHANNELS.PRIVACY.ADD_EXCLUDED_APP,
  IPC_CHANNELS.PRIVACY.REMOVE_EXCLUDED_APP,
  IPC_CHANNELS.PRIVACY.GET_EXCLUDED_PATTERNS,
  IPC_CHANNELS.PRIVACY.ADD_EXCLUDED_PATTERN,
  IPC_CHANNELS.PRIVACY.REMOVE_EXCLUDED_PATTERN,
  IPC_CHANNELS.PRIVACY.GET_PRIVATE_MODE,
  IPC_CHANNELS.PRIVACY.SET_PRIVATE_MODE,
  IPC_CHANNELS.PRIVACY.GET_DATA_RETENTION,
  IPC_CHANNELS.PRIVACY.SET_DATA_RETENTION,
  IPC_CHANNELS.PRIVACY.EXPORT_ALL_DATA,
  IPC_CHANNELS.PRIVACY.DELETE_ALL_DATA,
  IPC_CHANNELS.PRIVACY.APPLY_DATA_RETENTION,
  // Shortcuts
  IPC_CHANNELS.SHORTCUTS.GET_ALL,
  IPC_CHANNELS.SHORTCUTS.GET_BY_ID,
  IPC_CHANNELS.SHORTCUTS.UPDATE,
  IPC_CHANNELS.SHORTCUTS.RESET_ALL,
  IPC_CHANNELS.SHORTCUTS.SET_ENABLED,
  // Themes
  IPC_CHANNELS.THEMES.GET_CURRENT,
  IPC_CHANNELS.THEMES.SET_THEME,
  IPC_CHANNELS.THEMES.GET_AVAILABLE,
  // App
  IPC_CHANNELS.APP.GET_VERSION,
  IPC_CHANNELS.APP.GET_ONBOARDING_STATUS,
  IPC_CHANNELS.APP.SET_ONBOARDING_COMPLETE
];

export const RECEIVE_CHANNELS = [
  IPC_CHANNELS.TRACKING.WINDOW_CHANGED,
  IPC_CHANNELS.TRACKING.IDLE_CHANGED,
  IPC_CHANNELS.TRACKING.STATE_CHANGED,
  IPC_CHANNELS.TRACKING.IDLE_PROMPT,
  IPC_CHANNELS.APP.NAVIGATE,
  IPC_CHANNELS.LIMITS.WARNING,
  IPC_CHANNELS.LIMITS.EXCEEDED,
  IPC_CHANNELS.LIMITS.BLOCKED,
  IPC_CHANNELS.PRIVACY.PRIVATE_MODE_CHANGED,
  IPC_CHANNELS.SHORTCUTS.TRIGGERED
];